name       : budgie-extras
version    : 0.8.3
release    : 1
source     :
    - https://github.com/UbuntuBudgie/budgie-extras/archive/v0.8.3.tar.gz : 055a3f710f33342ad665f8ac945bc39f54edf57683731144f3648deae4f346b6
license    : GPL-3.0-or-later
component  : budgie.desktop
summary    : WeatherShowII is a completely rewritten version of the existing python WeatherShow applet
description: |
    WeatherShowII is a completely rewritten version of the existing python WeatherShow applet. It merges the functionality of Budgie Weather applet (showing weather in the panel) and WeatherShow. Each of the modules: weather forecast, weather in the panel and weather on the desktop can be switched on and of.
builddeps  :
            - pkgconfig(gtk+-3.0)
            - pkgconfig(budgie-1.0)
            - pkgconfig(budgie-theme-1.0)
            - pkgconfig(gee-0.8)
            - pkgconfig(libsoup-2.4)
            - pkgconfig(libpeas-gtk-1.0)
            - pkgconfig(json-glib-1.0)
            - pkgconfig(libpeas-gtk-1.0)
            - pkgconfig(libwnck-3.0)
            - meson
            - vala
setup      : |
    %meson_configure
build      : |
    mkdir build && cd build
    meson --buildtype plain -Dbuild-all=false -Dbuild-weathershow=true --prefix=/usr --libdir=/usr/lib --datadir=/usr/share ..
install    : |
    %meson_install
